namespace Application.Dtos
{
    /// <summary>
    /// Code is intentionally absent from ItemSaveRequest — it's server-generated by
    /// ItemCodeService from the chosen category, never client-settable.
    /// </summary>
    public sealed class ItemDto
    {
        public int Id { get; set; }
        public string? Code { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        public bool? IsActive { get; set; }
        public int? CategoryId { get; set; }
        public string? CategoryName { get; set; }
        public int? UnitId { get; set; }
        public string? UnitName { get; set; }
    }

    public class ItemSaveRequest
    {
        public string? Name { get; set; }
        public string? Description { get; set; }
        public bool? IsActive { get; set; }
        public int? CategoryId { get; set; }
        public int? UnitId { get; set; }
    }

    public sealed class ItemCreateRequest : ItemSaveRequest
    {
    }

    public sealed class ItemUpdateRequest : ItemSaveRequest
    {
    }
}
